Fixes typos and wrong filepath
delvedor/fastify-example pull request #3
Opened 2021-02-07 19:02 UTC by marquicodes

Very nice project! It came on time as I was looking how to use Svelte with Fastify. 👍🏼

I found a few typos and a wrong file path.

Great job.

2021-02-08 07:53 UTC, delvedor requested changes
Thanks! Can you rebase on master?

2021-02-09 07:21 UTC, delvedor commented on test/helper.js
> +process.env.ALLOWED_USERS = 'foo@bar.com'
This change is already in `main`, not sure why it's present here as well. 🤔

2021-02-09 08:52 UTC, delvedor approved these changes
My bad! I meant to merge the main branch in yours!
These changes are ok, thanks for contributing!

2021-02-09 08:52 UTC, merged

2021-02-09 11:12 UTC, marquicodes commented
Sorry for misunderstanding. Thank you for creating this very useful example.